FPS = 15 # spillet gikk alt for fort med 60FPS
BREDDE = 600
HOYDE = 600
TID_MELLOM_EPLER = 2
ANTALL_RADER = 20
ANTALL_KOLONNER = 20
CELLEHOYDE = HOYDE / ANTALL_RADER
CELLEBREDDE = BREDDE / ANTALL_RADER
